version: "2"
engines:
  govet:
    enabled: true
  golint:
    enabled: true
  gofmt:
    enabled: true

exclude_paths:
  - "Godeps"
  - "test_fixtures"
  - "vendor"
  - "/vm/instruction.go"
  - "/vm/vm.go"

ratings:
  paths:
    - "**.go"
